name       : libxpresent
version    : 1.0.0
release    : 2
source     :
    - https://www.x.org/releases/individual/lib/libXpresent-1.0.0.tar.gz : 92f1bdfb67ae2ffcdb25ad72c02cac5e4912dc9bc792858240df1d7f105946fa
license    : MIT
component  : xorg.library
summary    : X11 presentation library
description: |
    X11 presentation library
builddeps  :
    - pkgconfig(presentproto)
    - pkgconfig(xextproto)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(xrandr)
patterns   :
    - devel : /usr/share/man/man3
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
